<form class="form subscribe form-subscribe" ...>
    <div class="subscribe-form-container">
        <input 
            name="email" 
            type="email" 
            id="newsletter" 
            placeholder="Enter address" 
            data-validate="{required:true, 'validate-email':true}" />
        <div class="actions">
            <button class="action subscribe primary" title="Subscribe" type="submit" aria-label="Subscribe">
                <span>Subscribe</span>
            </button>
        </div>            
    </div>
</form>
